# -*- coding: utf-8 -*-
"""IPL analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmXO-NuPkIXzpZH0ZsRfJNWWA77A_-9f
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""loading of the  data"""

match_df=pd.read_csv('/content/Dataset1.csv')
match_df.head(n=6)

delivery_df=pd.read_csv('/content/IPL_Ball_by_Ball_2008_2022.csv')
delivery_df.head(n=10)

"""knowing about the data"""

delivery_df.info()

match_df.info()

"""**Data Cleaning**

It can be seen from the data that the column 'method' has only 19 non null values which is too low. So in that case we just have to remove it because there is no way we can fix this amount of NAN values
"""

match_df['method'].isnull().sum()

match_df=match_df.drop('method',axis=1)
match_df.head()

"""there are some columns which has some few nan values so we will fill something nan values according to the requirement like for example In "city" we can just label it like 'unknown' since we dont know which city is this and may be this unknown city has more winning or losing rate on batting first, we dont know exactly
while in 'Superover' we can fill it with most frequent values since the value of superover happenend or not be either 0 or 1 so it must be something in between it.
"""

col=['City','WinningTeam','Player_of_Match','SuperOver']
match_df['Margin']=match_df['Margin'].fillna(0)
match_df[col]=match_df[col].fillna('unknown')

match_df.info()

"""There are some teams that have only changed their names, while the team itself remains the same, so we can consider them as a single team.
like (Delhi Daredevils and Delhi Capitals, while they both are same franchise they just changed their names).
So in that case, we can just merge the teams.That will help in making the data simpler
"""

team_map={
    'Royal Challengers Bangalore' : 'Royal Challengers Bengaluru',
    'Delhi Daredevils': 'Delhi Capitals',
    'Rising Pune Supergiants': 'Rising Pune Supergiant',
    'Deccan Chargers': 'Sunrisers Hyderabad',
    'Gujarat Lions' : 'Gujarat Titans',
    'Kings XI Punjab': 'Punjab Kings'
}
match_df.replace(team_map, inplace=True)
delivery_df.replace(team_map, inplace=True)

match_df.City.unique()

"""there were some city values which are labeled as unknown so we can find the venue so that city can be known and then it can be changed"""

match_df[match_df['City']=='unknown']['Venue'].unique()

match_df.loc[match_df.Venue == 'Dubai International Cricket Stadium', 'City'] = 'Dubai'
match_df.loc[match_df.Venue == 'Sharjah Cricket Stadium', 'City'] = 'Sharjah'

match_df.duplicated().sum()

match_df['Venue'].nunique()

"""there were several venues which were same they got renamed or written in different way"""

stadium_map = {

    "Sardar Patel Stadium, Motera": "Narendra Modi Stadium",
    "Narendra Modi Stadium, Ahmedabad": "Narendra Modi Stadium",

    "Feroz Shah Kotla": "Arun Jaitley Stadium",
    "Arun Jaitley Stadium, Delhi": "Arun Jaitley Stadium",


    "Eden Gardens, Kolkata": "Eden Gardens",
    "Wankhede Stadium, Mumbai": "Wankhede Stadium",
    "Brabourne Stadium, Mumbai": "Brabourne Stadium",
    "Dr DY Patil Sports Academy, Mumbai": "Dr DY Patil Sports Academy",
    "Maharashtra Cricket Association Stadium, Pune": "Maharashtra Cricket Association Stadium",


    "MA Chidambaram Stadium, Chepauk, Chennai": "MA Chidambaram Stadium",
    "MA Chidambaram Stadium, Chepauk": "MA Chidambaram Stadium",


    "Punjab Cricket Association IS Bindra Stadium": "Punjab Cricket Association Stadium",
    "Punjab Cricket Association IS Bindra Stadium, Mohali": "Punjab Cricket Association Stadium",
    "Punjab Cricket Association Stadium, Mohali": "Punjab Cricket Association Stadium",


    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",


    "Rajiv Gandhi International Stadium, Uppal": "Rajiv Gandhi International Stadium",


    "Zayed Cricket Stadium, Abu Dhabi": "Sheikh Zayed Stadium"
}


match_df['Venue'] = match_df['Venue'].replace(stadium_map)

"""fixing deliveries.csv nan values"""

delivery_df[['player_out','kind','fielders_involved','extra_type']]=delivery_df[['player_out','kind','fielders_involved','extra_type']].fillna('none')

"""EDA for the match.csv"""

pd.crosstab(match_df['TossWinner'],match_df['Season'],values=match_df['MatchNumber']=='Final', aggfunc='sum')

match_df[(match_df['MatchNumber']=='Final')]['WinningTeam']

"""On examining both of the above tables i noticed something.There were some cases where the team who won most no. of Tosses, wins the whole league."""

perform=pd.crosstab(match_df['WinningTeam'],match_df['Season'])

plt.figure(figsize=(12,8))
sns.heatmap(perform , cmap='coolwarm')
plt.title("Heatmap of the no. of matches a team won in a particular season.",fontsize=18)
plt.savefig("team_wins.png",dpi=150)
plt.show()

most_wins=match_df['WinningTeam'].value_counts().head(10)

plt.figure(figsize=(12,10))
sns.barplot(x=most_wins.values,y=most_wins.index,color='green')
plt.title("Teams Won Most")
plt.savefig("Team_Win_Total",dpi=150)
plt.show

"""plot of the toss decision by all teams in a season from here it is clear that teams is in favor to choose fielding rather than batting on winning the toss"""

toss = pd.crosstab(match_df['Season'], match_df['TossDecision'])

toss.plot(kind='bar', stacked=True, figsize=(12,6))

plt.title("Toss Decision (Bat vs Field) by Season")
plt.xlabel("Season")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.savefig("toss_decision.png",dpi=150)
plt.show()

host=match_df['Venue'].value_counts().head(10)

plt.figure(figsize=(12,8))
sns.barplot(x=host.values,y=host.index,color='green')
plt.title("top 10 venues in which match hosted")
plt.savefig("host_venue.png",dpi=900)
plt.show

match_df['Venue'].nunique()

match_df['Venue'].value_counts(normalize=True)*100

"""There are around 33 venues.These many categories are hard to visualise so as we can see top 15 categories total carries 68 percent of total proportion so all others we can group them as 'other' so that visualisation of the venues across the seasons become possible and easier"""

match_df['Venue'].value_counts(normalize=True).head(20).sum()*100
counts=match_df['Venue'].value_counts()
total_categories = counts.nlargest(15).index
match_df['Venue'] = match_df['Venue'].apply(
    lambda x: x if x in total_categories else 'other'
)

toss = pd.crosstab(match_df['Season'], match_df['Venue'])
plt.figure(figsize=(12,8))
sns.lineplot(toss)
plt.title("Venues across seasons")
plt.savefig("Venues.png",dpi=900)
plt.show()

#players with most player of the match over all season
potm=match_df['Player_of_Match'].value_counts().head(10)

plt.figure(figsize=(12,8))
sns.barplot(x=potm.values,y=potm.index,color='green')
plt.title("Most Player Of The Match")
plt.savefig("potm.png",dpi=150)
plt.show

"""Pitch condition on basis of batting or bowling first"""

venue_cond=match_df.groupby(['Venue'])['WonBy'].value_counts().reset_index()
bat_w=venue_cond[venue_cond['WonBy']=='Wickets']
field_w=venue_cond[venue_cond['WonBy']=='Runs']
plt.figure(figsize=(12,8))
sns.barplot(x=bat_w['Venue'],y=bat_w['count'],data=bat_w, label='Won by bowling first', color='green')
sns.barplot(x=field_w['Venue'],y=field_w['count'],data=field_w, label='Won by batting first', color='blue')
plt.title("Matches Won by Wickets vs Runs at Different Venues")
plt.xlabel("Venue")
plt.ylabel("Number of Wins")
plt.xticks(rotation=90)
plt.legend()
plt.tight_layout()
plt.savefig("venue_reports.png",dpi=900)
plt.show()

"""it can be observed that mostly team who bowl first wins more than team who bat first maybe its because one a team bat then the other team can play according to their given target and they have the required figure like when to play more and when to leave the ball in order to win"""

venue_cond

"""EDA delivery.csv"""

batsman_runs=delivery_df.groupby('batter')['batsman_run'].sum().reset_index()
top_10=batsman_runs.sort_values(ascending=False,by='batsman_run').head(10)

plt.figure(figsize=(12,8))
sns.barplot(x=top_10['batsman_run'],y=top_10['batter'],data=top_10)
plt.savefig('Most_Run.png',dpi=150)
plt.show()

delivery_df['kind'].unique()

delivery_df

bowler_wickets = ['bowled', 'caught', 'caught and bowled', 'lbw', 'stumped', 'hit wicket']

delivery_df['is_bowler_wicket'] = delivery_df['kind'].isin(bowler_wickets)
bowler_wickets_data = delivery_df.groupby('bowler')['is_bowler_wicket'].sum().reset_index()
top_10_bowlers = bowler_wickets_data.sort_values(by='is_bowler_wicket',ascending=False).head(10)

plt.figure(figsize=(12,8))
sns.barplot(x=top_10_bowlers['is_bowler_wicket'],y=top_10_bowlers['bowler'],data=top_10_bowlers)
plt.title("Best Bowler of ALL time in IPL vs Wickets")
plt.savefig('Most_Wicket.png',dpi=150)
plt.show()

"""here we take the inning score for a match(2024 IPL FINALS) and analyze the score made per ball of the innings for that i made a separate database for that specific match and inning and then worked on that and plotted a scatter plot for the same."""

matchinfo_df = delivery_df[
    (delivery_df['ID'] == 1312200)].copy()

matchinfo_df['ball'] = (matchinfo_df['overs'] - 1) * 6 + matchinfo_df['ballnumber']

matchinfo_df = matchinfo_df.sort_values('ball')

matchinfo_df['cumulative_runs'] = matchinfo_df['total_run'].cumsum()
matchinfo_in1=matchinfo_df[(matchinfo_df['innings'] == 1)
].copy()
matchinfo_in2=matchinfo_df[(matchinfo_df['innings'] == 2)
].copy()

plt.figure(figsize=(10,5))
sns.scatterplot(x=matchinfo_in1['ball'],y= matchinfo_in1['cumulative_runs'],data=matchinfo_in1,alpha=1,)
sns.scatterplot(x=matchinfo_in2['ball'],y= matchinfo_in2['cumulative_runs'],data=matchinfo_in2,alpha=0.5)
plt.xlabel('Ball Number')
plt.ylabel('Cumulative Runs')
plt.title('Innings Progression')
plt.legend(['Inning 1', 'Inning 2'])
plt.savefig("Inning_score_final_scatter.png",dpi=150)
plt.show()

"""# Outlier Detection On an Inning Score

here is the outlier got through analyzing the first inning score of the match btw RCB and Pune.
"""

match_df[(match_df['Team1']=='Royal Challengers Bengaluru') & (match_df['Team2']=='Rising Pune Supergiant') & (match_df['Season']=='2016')]['ID']

outlier_df = delivery_df[
    (delivery_df['ID'] ==980969) & (delivery_df['innings'] == 1)
].copy()

outlier_df['ball'] = (outlier_df['overs'] - 1) * 6 + outlier_df['ballnumber']

outlier_df = outlier_df.sort_values('ball')

Q1 =outlier_df['total_run'].quantile(0.25)
Q3 = outlier_df['total_run'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers_iqr =outlier_df[(outlier_df['total_run'] < lower) | (outlier_df['total_run'] > upper)]
outliers_iqr

"""The Z-score method did not identify any outliers using the threshold |z| > 3, indicating that no innings scores lie more than three standard deviations away from the mean. This suggests that the distribution does not contain extreme values.
However, the IQR method identified several outliers. This difference arises because the IQR method is more robust to skewed data and can detect moderate deviations from the median, whereas the Z-score method is sensitive to the mean and standard deviation.
"""

from scipy.stats import zscore
outlier_df['z_score'] = zscore(outlier_df['total_run'])
outlier=outlier_df[np.abs(outlier_df['z_score'])>3]
outlier

"""in box plot also we can easily see the outliers"""

plt.figure(figsize=(12,8))
sns.boxplot(x=outlier_df['total_run'],data=outlier_df)
plt.savefig('Outlier_box.png')
plt.show()

"""here is the line chart for a single match . The total runs scored in a over in a single match


"""

run_over=delivery_df.groupby(['overs','innings','ID'])['total_run'].sum().reset_index()

plt.figure(figsize=(12,8))
# Filter the aggregated 'run_over' DataFrame for a specific match and innings
filtered_run_over1 = run_over[(run_over['innings'] == 1) & (run_over['ID'] == 1312200)]
filtered_run_over2 = run_over[(run_over['innings'] == 2) & (run_over['ID'] == 1312200)]

# Plot using the filtered DataFrame
sns.lineplot(x=filtered_run_over1['overs'],y=filtered_run_over1['total_run'],data=filtered_run_over1,label='Rajasthan Royals')
sns.lineplot(x=filtered_run_over2['overs'],y=filtered_run_over2['total_run'],data=filtered_run_over2,label='Gujarat Titans')
plt.title("Total Runs Distribution in Each Over")
plt.xlabel("Over")
plt.ylabel("Total Runs")
plt.legend()
plt.savefig("Total_Runs_Distribution.png",dpi=150)
plt.show()

match_df.info()

df_merge=match_df.merge(delivery_df,left_on='ID',right_on='ID')
df_merge.head(n=10)

df_merge.info()

#Total Runs Scored by Each team
Team_run=df_merge.groupby('BattingTeam')['total_run'].sum().reset_index()
plt.figure(figsize=(12,8))
sns.barplot(x=Team_run['BattingTeam'],y=Team_run['total_run'],data=Team_run)
plt.title("Total Runs Scored by Each Team")
plt.xlabel("Team")
plt.ylabel("Total Runs")
plt.xticks(rotation=90)
plt.savefig("Total_Runs_team.png",dpi=150)
plt.show

"""# Chi Square Test

Null Hypothesis: The match outcome is independent of the Toss Decision
Alternate Hypothesis: The match outcome has significally impact on the The Toss Decision
"""

match_df['toss_win_match_win']=(match_df['TossWinner']==match_df['WinningTeam'])
table=pd.crosstab(match_df['TossDecision'],match_df['toss_win_match_win'])
table

from scipy.stats import chi2_contingency
chi2,p,dof,expected=chi2_contingency(table)
print(p)
print(chi2)
print(dof)

"""We reject the Null Hypothesis,since the p is less than alpha(the significant value) we can say that toss decision does have a statistically significant impact on the match outcome.

# Prediction of Team Batting First Win or Not(Using Match Level Features at the time of Toss)

Feature Engineering and Feature Selection

Here i have used some engineered historical features to imporve the accuracy of my model because it was not performing well using only raw data
some of the historical engineered feature i included are like Team's recent wins and overall both team rate difference Team who is batting first and difference of how many times both team won by batting first
"""

match_df.info()

"""here i tried to get features like the team recent form and the overall team rate of the batting first team and batting second team. For that first i made a separate dataframes for Team 1 and Team 2 with the Winning Team and then giving them same feature as Team i concatenated them so that i can get their proper win rate ensuring that the same team can occur as team1 as well as team2"""

match_df['Date']=pd.to_datetime(match_df['Date'])

team1_df = match_df[['Date','Team1','WinningTeam']].copy()
team1_df.columns = ['Date','Team','WinningTeam']

team2_df = match_df[['Date','Team2','WinningTeam']].copy()
team2_df.columns = ['Date','Team','WinningTeam']

long_df = pd.concat([team1_df, team2_df])

long_df['win'] = (long_df['Team'] == long_df['WinningTeam']).astype(int)
long_df = long_df.sort_values('Date')

long_df['matches_played'] = long_df.groupby('Team').cumcount()
long_df['cum_wins'] = (
    long_df.groupby('Team')['win']
    .transform(lambda x: x.cumsum().shift(1))
    .fillna(0)
)

long_df['win_rate'] = long_df['cum_wins'] / (long_df['matches_played'] + 1)

"""With the Win rate and the Win feature we can extract features like recent win and the win rate difference. And point to note that the Win rate is calculated only using the past matches data to avoid data leakage."""

long_df['recent_wins'] = (
    long_df.groupby('Team')['win']
    .transform(lambda x: x.shift(1).rolling(5).sum())
)
long_df['recent_matches'] = (
    long_df.groupby('Team').cumcount().clip(upper=5)
)
long_df['recent_wins'] = long_df['recent_wins'].fillna(0)
long_df['recent_win_rate'] = (
    long_df['recent_wins'] / (long_df['recent_matches'] + 1)
)

team1_stats_long_df = long_df.iloc[:len(match_df)]
team2_stats_long_df = long_df.iloc[len(match_df):]

match_df['team1_rate'] = team1_stats_long_df['win_rate'].values
match_df['team2_rate'] = team2_stats_long_df['win_rate'].values
match_df['team1_rate_recent'] = team1_stats_long_df['recent_win_rate'].values
match_df['team2_rate_recent'] = team2_stats_long_df['recent_win_rate'].values

match_df['win_rate_diff'] = match_df['team1_rate'] - match_df['team2_rate']

match_df['batting_first_team'] = match_df.apply(
    lambda x: x['Team1'] if x['TossDecision']=='bat' and x['TossWinner']==x['Team1']
    else x['Team2'] if x['TossDecision']=='bat'
    else x['Team2'] if x['TossWinner']==x['Team1']
    else x['Team1'],
    axis=1
)

match_df['bat_first_rate'] = np.where(
    match_df['batting_first_team'] == match_df['Team1'],
    match_df['team1_rate'],
    match_df['team2_rate']
)

match_df['bat_second_rate'] = np.where(
    match_df['batting_first_team'] == match_df['Team1'],
    match_df['team2_rate'],
    match_df['team1_rate']
)

match_df['strength_diff'] = match_df['bat_first_rate'] - match_df['bat_second_rate']

match_df=match_df.drop(['team1_rate','team2_rate','bat_first_rate','bat_second_rate'],axis=1)

match_df['toss_bat'] = (match_df['TossDecision'] == 'bat').astype(int)

match_df['toss_bat']

""" we have to encode important categorical columns and columns which are not important can be dropped and also there are some columns which is decided after the match so we can also drop it.Matchnumber column is a type of mixed column so instead of relying on the number we can just form the separate column which has 3 or 4 categories such as playoff semifinal final and league matches"""

#dropping features that have high cardinality and also some irrelevant features
match_df=match_df.drop(['Umpire1','Umpire2','Team2Players','Team1Players','ID','City','Season','Date','Player_of_Match','TossDecision'],axis=1)
#post match data and we have to decide at the time of the toss
match_df=match_df.drop(['WinningTeam','SuperOver','Margin'],axis=1)
def stage(x):
  if 'Final' in x:
    return 'Final'
  elif 'Qualifier 2' in x or 'Eliminator' in x or 'Qualifier 1' in x or 'Elimination Final' in x or 'Qualifier' in x or '3rd Place Play-Off' in x :
    return 'Playoff'
  elif 'Semi Final' in x:
    return 'Semi Final'
  else:
    return 'League'

match_df['MatchStages'] = match_df['MatchNumber'].astype(str).apply(stage)
match_df=match_df.drop('MatchNumber',axis=1)
match_df['MatchStages'].head(10)

""" target column which is "did the team who won the toss and opt batting first won or not??"
"""

match_df['Target']=match_df['WonBy'].apply(lambda x : 1 if x=='Runs' else 0)
match_df=match_df.drop('WonBy',axis=1)
x=match_df.drop('Target',axis=1)
y=match_df['Target']

match_df.info()

"""80/20 train-test split"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

"""Using column transformer encoding categorical features and scaling numerical features whichever necessary"""

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
categorical_cols=['Team1','Team2','Venue','TossWinner','MatchStages','batting_first_team']
numerical_cols = ['strength_diff','team1_rate_recent', 'team2_rate_recent']
trans = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols),
        ('scaler', StandardScaler(), numerical_cols)
    ],
    force_int_remainder_cols=False
)

"""implementing logistic regression and training the model by passing through the pipeline"""

from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
pipe = Pipeline(steps = [
    ('step1', trans),
    ('step2', LogisticRegression())
])

"""Fitting and Evaluating the model"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import ConfusionMatrixDisplay, precision_score, recall_score, f1_score , roc_curve,auc
pipe.fit(x_train,y_train)

y_train_pred=pipe.predict(x_train)
train_accuracy=accuracy_score(y_train,y_train_pred)

y_test_pred=pipe.predict(x_test)
test_accuracy=accuracy_score(y_test,y_test_pred)

train_precision = precision_score(y_train, y_train_pred)
train_recall = recall_score(y_train, y_train_pred)
train_f1 = f1_score(y_train, y_train_pred)

test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1 = f1_score(y_test, y_test_pred)

metrics_table = pd.DataFrame({
    'Dataset': ['Training', 'Test'],
    'Accuracy': [train_accuracy, test_accuracy],
    'Precision': [train_precision, test_precision],
    'Recall': [train_recall, test_recall],
    'F1 Score': [train_f1, test_f1]
})

print(metrics_table)

metrics_table.to_csv("metrics_summary.csv", index=False)

ConfusionMatrixDisplay.from_predictions(y_test, y_test_pred)

plt.title("Confusion Matrix")
plt.savefig("confusion_matrix.png", dpi=150)
plt.show()

y_prob = pipe.predict_proba(x_test)[:, 1]

# Compute ROC
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

# AUC score
roc_auc = auc(fpr, tpr)

# Plot
plt.figure()
plt.plot(fpr, tpr, label="AUC = " + str(round(roc_auc, 3)))
plt.plot([0, 1], [0, 1])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()

plt.savefig("roc_curve.png", dpi=150)
plt.show()

print("AUC Score:", roc_auc)